### ISSUE TITLE
CSI_MCLK和SDC_D2 为什么可以相连呢

### ISSUE THREAD

**Issue by mttbx** [VeiLiang/BoloPi_PCB#2]
如题

**Comment by VeiLiang** [comment]
因为MCLK是要时钟输入的，F1C100S没有专门的CLK out，所以选择了PWM作为时钟输出；PWM输出最大频率为24Mhz。

**Comment by mttbx** [comment]
谢谢你的回复
SD卡还能正确运行吗？毕竟和它连接在一起了

**Comment by VeiLiang** [comment]
> 谢谢你的回复
> SD卡还能正确运行吗？毕竟和它连接在一起了

可以用，不过只能用1bit模式，毕竟io口不够。如果确实SD卡是需要4bit的话，MCLK只能断开，然后用有源晶振了

**Comment by mttbx** [comment]
还有个小问题，TP_Y1和PWM0连在一起了，而PWM0是给LED供电电路提供EN的，这样做可以吗，触摸屏不是又要LED供电又要输出坐标吗。

**Comment by VeiLiang** [comment]
> 还有个小问题，TP_Y1和PWM0连在一起了，而PWM0是给LED供电电路提供EN的，这样做可以吗，触摸屏不是又要LED供电又要输出坐标吗。

这个也是取舍问题了，一般不用默认的电阻触摸的。所以利用了其中的pwm0来作为背光控制。不能同时用

**Comment by mttbx** [comment]
谢谢指点，你的电路给了我启发。
